/**
 * Product catalog. Real SKUs and pricing pulled from the live thewowguys.com site.
 * For tonight's demo: chairs are real, other categories are placeholders for the same shape.
 *
 * In production this should come from the e-commerce backend / WooCommerce export.
 */

export type ProductCategory =
  | "seating"
  | "desks"
  | "conference"
  | "pods"
  | "healthcare"
  | "education"
  | "reception"
  | "preowned";

export interface Product {
  sku: string;
  name: string;
  category: ProductCategory;
  subCategory?: string;
  /** Omit for showcase products that quote on request */
  price?: number;
  /** When true, the price renders as a "Starting at" from-price. */
  startingAt?: boolean;
  originalPrice?: number;
  description: string;
  image?: string;
  /** Internal note: e.g. "Ergonomic mesh task chair" */
  type?: string;
}

const FALLBACK_IMAGE = "/product-placeholder.svg";

export const PRODUCTS: Product[] = [
  // SEATING. "Basic Tasking and Ergonomic" look. Real curated photos from Cesar (Jun 5, 2026).
  // Photos/SKUs/names are locked. Per-chair "starting at" prices set Jun 5, 2026 (approximate,
  // shown as "Starting at ~$X"). They lead the array so they head the look page.
  {
    sku: "HVOF-T-01",
    name: "HVOF T-01",
    category: "seating",
    subCategory: "Task",
    price: 449,
    startingAt: true,
    description: "Ergonomic task seating built for full eight-hour workdays.",
    image: "/products/hvof-t-01.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-02",
    name: "HVOF T-02",
    category: "seating",
    subCategory: "Task",
    price: 559,
    startingAt: true,
    description: "Adjustable task chair tuned for everyday desk work.",
    image: "/products/hvof-t-02.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-03",
    name: "HVOF T-03",
    category: "seating",
    subCategory: "Task",
    price: 299,
    startingAt: true,
    description: "All-day task seating. Adjustable, durable, and built to spec.",
    image: "/products/hvof-t-03.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-04",
    name: "HVOF T-04",
    category: "seating",
    subCategory: "Task",
    price: 339,
    startingAt: true,
    description: "Comfort-first task chair for desks, workstations, and open plans.",
    image: "/products/hvof-t-04.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-05",
    name: "HVOF T-05",
    category: "seating",
    subCategory: "Task",
    price: 229,
    startingAt: true,
    description: "Supportive task seating with adjustable height and tilt.",
    image: "/products/hvof-t-05.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-06",
    name: "HVOF T-06",
    category: "seating",
    subCategory: "Task",
    price: 399,
    startingAt: true,
    description: "Everyday ergonomic chair for focused, heads-down work.",
    image: "/products/hvof-t-06.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-07",
    name: "HVOF T-07",
    category: "seating",
    subCategory: "Task",
    price: 489,
    startingAt: true,
    description: "Ergonomic task seating built for full eight-hour workdays.",
    image: "/products/hvof-t-07.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-08",
    name: "HVOF T-08",
    category: "seating",
    subCategory: "Task",
    price: 479,
    startingAt: true,
    description: "Adjustable task chair tuned for everyday desk work.",
    image: "/products/hvof-t-08.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-09",
    name: "HVOF T-09",
    category: "seating",
    subCategory: "Task",
    price: 589,
    startingAt: true,
    description: "All-day task seating. Adjustable, durable, and built to spec.",
    image: "/products/hvof-t-09.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-10",
    name: "HVOF T-10",
    category: "seating",
    subCategory: "Task",
    price: 399,
    startingAt: true,
    description: "Comfort-first task chair for desks, workstations, and open plans.",
    image: "/products/hvof-t-10.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-11",
    name: "HVOF T-11",
    category: "seating",
    subCategory: "Task",
    price: 549,
    startingAt: true,
    description: "Supportive task seating with adjustable height and tilt.",
    image: "/products/hvof-t-11.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-12",
    name: "HVOF T-12",
    category: "seating",
    subCategory: "Task",
    price: 599,
    startingAt: true,
    description: "Everyday ergonomic chair for focused, heads-down work.",
    image: "/products/hvof-t-12.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-13",
    name: "HVOF T-13",
    category: "seating",
    subCategory: "Task",
    price: 649,
    startingAt: true,
    description: "Ergonomic task seating built for full eight-hour workdays.",
    image: "/products/hvof-t-13.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-14",
    name: "HVOF T-14",
    category: "seating",
    subCategory: "Task",
    price: 459,
    startingAt: true,
    description: "Adjustable task chair tuned for everyday desk work.",
    image: "/products/hvof-t-14.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-15",
    name: "HVOF T-15",
    category: "seating",
    subCategory: "Task",
    price: 399,
    startingAt: true,
    description: "All-day task seating. Adjustable, durable, and built to spec.",
    image: "/products/hvof-t-15.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-16",
    name: "HVOF T-16",
    category: "seating",
    subCategory: "Task",
    price: 399,
    startingAt: true,
    description: "Comfort-first task chair for desks, workstations, and open plans.",
    image: "/products/hvof-t-16.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-17",
    name: "HVOF T-17",
    category: "seating",
    subCategory: "Task",
    price: 859,
    startingAt: true,
    description: "Supportive task seating with adjustable height and tilt.",
    image: "/products/hvof-t-17.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-18",
    name: "HVOF T-18",
    category: "seating",
    subCategory: "Task",
    price: 599,
    startingAt: true,
    description: "Everyday ergonomic chair for focused, heads-down work.",
    image: "/products/hvof-t-18.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-19",
    name: "HVOF T-19",
    category: "seating",
    subCategory: "Task",
    price: 795,
    startingAt: true,
    description: "Ergonomic task seating built for full eight-hour workdays.",
    image: "/products/hvof-t-19.jpg",
    type: "Task seating",
  },
  {
    sku: "HVOF-T-20",
    name: "HVOF T-20",
    category: "seating",
    subCategory: "Task",
    price: 695,
    startingAt: true,
    description: "Adjustable task chair tuned for everyday desk work.",
    image: "/products/hvof-t-20.jpg",
    type: "Task seating",
  },

  // SEATING. "Conference and Executive" look. Real curated photos from Cesar (Jun 12, 2026).
  // Photos/SKUs/names are locked (HVOF CE-01..CE-14). Prices are pending from the team. They
  // will be added as "Starting at ~$X" (with startingAt: true) once provided, the same way the
  // T-series was priced. Until then these render "Quote on request". Mid-back chairs are
  // Conference, high-back chairs are Executive, so the "Conference and Executive" look fills both.
  {
    sku: "HVOF-CE-01",
    name: "HVOF CE-01",
    category: "seating",
    subCategory: "Conference",
    description: "Clean-lined conference chair in white leather with polished aluminum arms and base.",
    image: "/products/hvof-ce-01.jpg",
    type: "Conference seating",
  },
  {
    sku: "HVOF-CE-02",
    name: "HVOF CE-02",
    category: "seating",
    subCategory: "Executive",
    description: "High-back executive chair in cognac leather with sculpted wood side panels.",
    image: "/products/hvof-ce-02.jpg",
    type: "Executive seating",
  },
  {
    sku: "HVOF-CE-03",
    name: "HVOF CE-03",
    category: "seating",
    subCategory: "Conference",
    description: "Mid-back conference seating in slate with adjustable arms and a polished base.",
    image: "/products/hvof-ce-03.jpg",
    type: "Conference seating",
  },
  {
    sku: "HVOF-CE-04",
    name: "HVOF CE-04",
    category: "seating",
    subCategory: "Executive",
    description: "Ribbed high-back executive chair in black with polished chrome arms.",
    image: "/products/hvof-ce-04.jpg",
    type: "Executive seating",
  },
  {
    sku: "HVOF-CE-05",
    name: "HVOF CE-05",
    category: "seating",
    subCategory: "Conference",
    description: "Ribbed mid-back conference chair in black with polished chrome arms.",
    image: "/products/hvof-ce-05.jpg",
    type: "Conference seating",
  },
  {
    sku: "HVOF-CE-06",
    name: "HVOF CE-06",
    category: "seating",
    subCategory: "Executive",
    description: "High-back executive chair in soft gray with a channel-stitched back.",
    image: "/products/hvof-ce-06.jpg",
    type: "Executive seating",
  },
  {
    sku: "HVOF-CE-07",
    name: "HVOF CE-07",
    category: "seating",
    subCategory: "Executive",
    description: "Channel-stitched high-back executive chair in white leather.",
    image: "/products/hvof-ce-07.jpg",
    type: "Executive seating",
  },
  {
    sku: "HVOF-CE-08",
    name: "HVOF CE-08",
    category: "seating",
    subCategory: "Executive",
    description: "Executive high-back in cognac leather with bronze-finish arms and base.",
    image: "/products/hvof-ce-08.jpg",
    type: "Executive seating",
  },
  {
    sku: "HVOF-CE-09",
    name: "HVOF CE-09",
    category: "seating",
    subCategory: "Executive",
    description: "Tall executive chair in taupe leather on a matte black frame.",
    image: "/products/hvof-ce-09.jpg",
    type: "Executive seating",
  },
  {
    sku: "HVOF-CE-10",
    name: "HVOF CE-10",
    category: "seating",
    subCategory: "Executive",
    description: "Ribbed high-back executive chair in black leather with chrome cantilever arms.",
    image: "/products/hvof-ce-10.jpg",
    type: "Executive seating",
  },
  {
    sku: "HVOF-CE-11",
    name: "HVOF CE-11",
    category: "seating",
    subCategory: "Conference",
    description: "Mid-back conference chair in mocha leather with polished aluminum arms.",
    image: "/products/hvof-ce-11.jpg",
    type: "Conference seating",
  },
  {
    sku: "HVOF-CE-12",
    name: "HVOF CE-12",
    category: "seating",
    subCategory: "Executive",
    description: "Big-and-tall executive chair in black leather with a reinforced polished base.",
    image: "/products/hvof-ce-12.jpg",
    type: "Executive seating",
  },
  {
    sku: "HVOF-CE-13",
    name: "HVOF CE-13",
    category: "seating",
    subCategory: "Executive",
    description: "Traditional high-back executive chair in black leather with a pillow-top headrest.",
    image: "/products/hvof-ce-13.jpg",
    type: "Executive seating",
  },
  {
    sku: "HVOF-CE-14",
    name: "HVOF CE-14",
    category: "seating",
    subCategory: "Executive",
    description: "High-back executive chair in black leather with polished aluminum arms.",
    image: "/products/hvof-ce-14.jpg",
    type: "Executive seating",
  },

  // DESKS, photos pulled from HVOF's curated catalog
  {
    sku: "HVOF-DESK-SS72",
    name: "Sit-Stand Desk 72\"",
    category: "desks",
    subCategory: "Sit-Stand",
    price: 1149,
    description: "Electric height-adjustable sit-stand desk, 72\" laminate top, 3-stage column.",
    image: "/products/HVOF-DESK-SS72.png",
  },
  {
    sku: "HVOF-DESK-EXEC",
    name: "Executive L-Desk",
    category: "desks",
    subCategory: "Executive",
    price: 2899,
    description: "Walnut veneer L-shaped executive desk with integrated cable management.",
    image: "/products/HVOF-DESK-EXEC.png",
  },
  {
    sku: "HVOF-DESK-BENCH",
    name: "Benching Workstation",
    category: "desks",
    subCategory: "Benching",
    price: 1849,
    description: "Open-plan benching system. Modular, expandable, available in 4-, 6-, 8-seat configurations.",
    image: "/products/HVOF-DESK-BENCH.png",
  },

  // CONFERENCE
  {
    sku: "HVOF-CONF-12FT",
    name: "12 ft Conference Table",
    category: "conference",
    subCategory: "Boardroom",
    price: 4299,
    description: "Boat-shape conference table on slab base. Walnut, oak, and cypress finishes available.",
    image: "/products/HVOF-CONF-12FT.png",
  },

  // ---- Showcase products (no fixed price, quote on request) ----
  // These reflect the lines, brands, and spaces shown on thewowguys.com
  // category pages. Images are sourced from the live WP CDN (whitelisted in next.config.ts).

  // DESKS, additional showcase
  {
    sku: "HVOF-DESK-LOGIFLEX-WELLINGTON",
    name: "Logiflex Wellington Executive",
    category: "desks",
    subCategory: "Executive",
    description: "Veneer-front executive desk, full modesty, integrated cable management. Logiflex US-built.",
    image: "https://thewowguys.com/wp-content/uploads/2024/06/Webpage-Product-Gallery-Desks-CollabAreas-Logiflex1.png",
  },
  {
    sku: "HVOF-DESK-AIS-OXYGEN",
    name: "AIS Oxygen Desking",
    category: "desks",
    subCategory: "Open Plan",
    description: "AIS Oxygen open-plan desking with shared power and integrated screens. Configurable for 2 to 12 seats.",
    image: "https://thewowguys.com/wp-content/uploads/2024/06/Webpage-Product-Gallery-Desks-CollabAreas-AISOxygen.png",
  },
  {
    sku: "HVOF-DESK-AIS-CALIBRATE",
    name: "AIS Calibrate Casegoods",
    category: "desks",
    subCategory: "Private Office",
    description: "Calibrate private-office casegoods. Storage, returns, and laminate or veneer tops to match.",
    image: "https://thewowguys.com/wp-content/uploads/2024/06/Webpage-Product-Gallery-Desks-CollabAreas-AIS1-1.png",
  },
  {
    sku: "HVOF-DESK-COE-COLLAB",
    name: "COE Collaborative Workstation",
    category: "desks",
    subCategory: "Collaborative",
    description: "COE collaborative workstation, designed for huddle-style team areas with sit-stand options.",
    image: "https://thewowguys.com/wp-content/uploads/2024/06/Webpage-Product-Gallery-CollabAreas-COE2-1.png",
  },
  {
    sku: "HVOF-DESK-COE-DESKING",
    name: "COE Desking System",
    category: "desks",
    subCategory: "Open Plan",
    description: "Modular COE desking with shared returns, integrated power, and matching storage.",
    image: "https://thewowguys.com/wp-content/uploads/2024/06/Webpage-Product-Gallery-Desking-COE12-1.png",
  },
  {
    sku: "HVOF-DESK-COE-DESKING-13",
    name: "COE Desking 13-series",
    category: "desks",
    subCategory: "Open Plan",
    description: "Bench-style COE desking, 6 to 8 seat configurations with integrated screen and shared power.",
    image: "https://thewowguys.com/wp-content/uploads/2024/06/Webpage-Product-Gallery-Desking-COE13.png",
  },
  {
    sku: "HVOF-DESK-COE-DESKING-15",
    name: "COE Desking 15-series",
    category: "desks",
    subCategory: "Open Plan",
    description: "COE workstation cluster with privacy screens. Sit-stand option per seat.",
    image: "https://thewowguys.com/wp-content/uploads/2024/06/Webpage-Product-Gallery-Desking-COE15.png",
  },
  {
    sku: "HVOF-DESK-LOGIFLEX-PRIVATE",
    name: "Logiflex Private Office Suite",
    category: "desks",
    subCategory: "Private Office",
    description: "Logiflex private-office suite with desk, return, credenza, and matching wall storage.",
    image: "https://thewowguys.com/wp-content/uploads/2024/06/Webpage-Product-Gallery-Desks-CollabAreas-Logiflex2.png",
  },
  {
    sku: "HVOF-DESK-LOGIFLEX-MANHATTAN",
    name: "Logiflex Manhattan Executive",
    category: "desks",
    subCategory: "Executive",
    description: "Manhattan-line executive desk. Dark walnut veneer with brushed-nickel hardware.",
    image: "https://thewowguys.com/wp-content/uploads/2024/06/Webpage-Product-Gallery-Desks-PRIVATE-OFFICES-LogiManhattan1.png",
  },
  {
    sku: "HVOF-DESK-OFS-CLASSIC",
    name: "OFS Classic Casegoods",
    category: "desks",
    subCategory: "Private Office",
    description: "OFS Classic-line private office casegoods. Traditional veneer with modesty panel and matching credenza.",
    image: "https://thewowguys.com/wp-content/uploads/2024/06/Webpage-Product-Gallery-Desks-PRIVATE-OFFICES-OFSClassic.png",
  },
  {
    sku: "HVOF-DESK-OFS-PULSE",
    name: "OFS Pulse Casegoods",
    category: "desks",
    subCategory: "Private Office",
    description: "OFS Pulse line. Contemporary laminate desk with file-storage pedestal and overhead.",
    image: "https://thewowguys.com/wp-content/uploads/2024/06/Webpage-Product-Gallery-Desks-PRIVATE-OFFICES-OFSPulse.png",
  },
  {
    sku: "HVOF-DESK-GLOBAL-GENOA",
    name: "Global Genoa Executive",
    category: "desks",
    subCategory: "Executive",
    description: "Global Genoa-series executive desk with cherry veneer and integrated cable trough.",
    image: "https://thewowguys.com/wp-content/uploads/2024/06/Webpage-Product-Gallery-Desks-PRIVATE-OFFICES-GlobalGenoa.png",
  },
  {
    sku: "HVOF-DESK-GLOBAL-ADAPT",
    name: "Global Adaptabilities",
    category: "desks",
    subCategory: "Executive",
    description: "Adaptabilities private-office system with sit-stand return and matching storage.",
    image: "https://thewowguys.com/wp-content/uploads/2024/06/Webpage-Product-Gallery-Desks-PRIVATE-OFFICES-GlobalAdaptabilities.png",
  },
  {
    sku: "HVOF-DESK-DARRAN-CAPITOL",
    name: "Darran Capitol Casegoods",
    category: "desks",
    subCategory: "Executive",
    description: "Darran Capitol-line casegoods. Premium veneer, hand-finished edge banding, executive credenza.",
    image: "https://thewowguys.com/wp-content/uploads/2024/06/Webpage-Product-Gallery-Desks-PRIVATE-OFFICES-DarranCapitol.png",
  },

  // CONFERENCE, additional showcase
  {
    sku: "HVOF-CONF-ENWORK-ADVENTURE",
    name: "Enwork Adventure Conference",
    category: "conference",
    subCategory: "Boardroom",
    description: "Enwork Adventure series conference table. Boat-shape and racetrack tops on slab or panel bases.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/Enwork_Adventure_Conference_Table_0821_resize_52145e5117869aa50425c0a5f0eb3b0c.jpg",
  },
  {
    sku: "HVOF-CONF-ENWORK-EQUILIBRIUM",
    name: "Enwork Equilibrium Conference",
    category: "conference",
    subCategory: "Boardroom",
    description: "Equilibrium series with veneer or laminate tops. Specced for engineering firms and creative agencies.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/Enwork_Equilibrium_Conference_Engineering_Firm_Client_Install_2024_resize_52145e5117869aa50425c0a5f0eb3b0c.jpg",
  },
  {
    sku: "HVOF-CONF-ENWORK-STEALTH",
    name: "Enwork Stealth Table + Credenza",
    category: "conference",
    subCategory: "Boardroom",
    description: "Stealth conference table paired with matching credenza. technology-ready cable channel and grommet plate.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/Enwork_Stealth_Conference_Table_and_Credenza_0720_resize_52145e5117869aa50425c0a5f0eb3b0c.jpg",
  },
  {
    sku: "HVOF-CONF-COE-10FT-BOAT",
    name: "COE 10 ft Boat-shape on Slab",
    category: "conference",
    subCategory: "Boardroom",
    description: "10 ft boat-shape conference table on slab base. Walnut, oak, white-oak, and laminate finishes.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/COE-10-foot-boat-shape-conference-table-on-slab-base.jpg",
  },
  {
    sku: "HVOF-CONF-COE-8FT-ELLIPTICAL",
    name: "COE 8 ft on Elliptical Base",
    category: "conference",
    subCategory: "Mid-size",
    description: "8 ft elliptical-base table. Right-sized for 6-person rooms with full technology cable management.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/COE-8-foot-on-eliptical-base.jpg",
  },
  {
    sku: "HVOF-CONF-LIGOURI",
    name: "Ligouri Conference Suite",
    category: "conference",
    subCategory: "Boardroom",
    description: "Ligouri-style boardroom suite. Custom inlay top with matching credenza available.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/Ligouri_Main_Beauty_042621web_resize_52145e5117869aa50425c0a5f0eb3b0c.jpg",
  },
  {
    sku: "HVOF-CONF-LOGIFLEX-WELLINGTON",
    name: "Logiflex Wellington Conference",
    category: "conference",
    subCategory: "Boardroom",
    description: "Logiflex Wellington line. Veneer-front conference table for 8 to 14 seats.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/logiflex_Conference_Wellington_C003b.jpg",
  },
  {
    sku: "HVOF-CONF-LOGIFLEX-HOWARD",
    name: "Logiflex Howard Conference",
    category: "conference",
    subCategory: "Boardroom",
    description: "Howard-series conference table with rectangular top and dual slab bases.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/logiflex_Conference_Howard_c001b_fb.jpg",
  },
  {
    sku: "HVOF-CONF-LOGIFLEX-ARROW",
    name: "Logiflex Arrow Conference",
    category: "conference",
    subCategory: "Mid-size",
    description: "Arrow-series conference table. Boat-shape with chrome trumpet base.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/logiflex_Conference_Arrow_c001b_fb.jpg",
  },
  {
    sku: "HVOF-CONF-LOGIFLEX-RECTANGULAR",
    name: "Logiflex Rectangular Conference",
    category: "conference",
    subCategory: "Training",
    description: "Rectangular conference and training table. Modular for flip-top training-room reconfigurations.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/logiflex_Conference_Rectangular_C002b.jpg",
  },
  {
    sku: "HVOF-CONF-STATEMENT-PINNACLE",
    name: "Statement Pinnacle Walnut",
    category: "conference",
    subCategory: "Boardroom",
    description: "Statement-line conference table in pinnacle walnut. Live-edge plank top option.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/Statement_60x240_w_BPG_Pinnacle_Walnut_033023_resize_52145e5117869aa50425c0a5f0eb3b0c.jpg",
  },
  {
    sku: "HVOF-CONF-STATEMENT-LIVE-EDGE",
    name: "Statement Live-Edge Walnut",
    category: "conference",
    subCategory: "Boardroom",
    description: "Statement table with live-edge walnut top. Custom-inlay with brushed steel base.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/Statement_Conference_Table_with_Live_Edge_Walnut_Plank_Top_080222_resize_52145e5117869aa50425c0a5f0eb3b0c.jpg",
  },
  {
    sku: "HVOF-CONF-JSI-ROMY",
    name: "JSI Romy Conference",
    category: "conference",
    subCategory: "Mid-size",
    description: "JSI Romy-line meeting table. Soft-edge top with paired or quad bases.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/jsi_romy_enviro_00002.jpg",
  },
  {
    sku: "HVOF-CONF-JSI-WALDEN",
    name: "JSI Walden Conference",
    category: "conference",
    subCategory: "Mid-size",
    description: "Walden-line meeting table with finished cable management. Walnut, cherry, or laminate.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/jsi_walden_comp_00004.jpg",
  },
  {
    sku: "HVOF-CONF-COSMO-UPHOLSTERED",
    name: "COE Cosmo Conference",
    category: "conference",
    subCategory: "Boardroom",
    description: "COE Cosmo conference suite with integrated technology cable channel and matching credenza.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/Media_Gallery_Environment_Thumb_cosmo_upholstered_681x322.jpg",
  },
  {
    sku: "HVOF-CONF-EXPANSE",
    name: "Expanse 6 ft Kingswood",
    category: "conference",
    subCategory: "Mid-size",
    description: "Expanse-line table in medium-tone Kingswood. Integrated grommet and adjustable bases.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/Expanse_72x360_Medium_Tone_Kingswood_031522_resize_52145e5117869aa50425c0a5f0eb3b0c.jpg",
  },
  {
    sku: "HVOF-CONF-VOU",
    name: "VOU Conference",
    category: "conference",
    subCategory: "Mid-size",
    description: "VOU-line conference table. Compact 100-degree wedge for 6-person huddle rooms.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/VOU_V_100deg_Scene_4_16x9_072524_resize_52145e5117869aa50425c0a5f0eb3b0c.jpg",
  },

  // HEALTHCARE
  {
    sku: "HVOF-HC-3105",
    name: "Patient Lounge 3105",
    category: "healthcare",
    subCategory: "Lounge",
    description: "Single-seat patient lounge chair. Bariatric-rated frame, replaceable upholstery panels, antimicrobial finish.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/3105-0.jpg",
  },
  {
    sku: "HVOF-HC-3140",
    name: "Patient Recliner 3140",
    category: "healthcare",
    subCategory: "Recliner",
    description: "Three-position medical recliner. Hand-control hydraulics, IV pole-compatible, full vinyl wrap.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/3140-0-20221213033739.jpg",
  },
  {
    sku: "HVOF-HC-13898",
    name: "Modular Healthcare Series 13898",
    category: "healthcare",
    subCategory: "Modular",
    description: "Ganged modular seating for waiting rooms. ADA-compliant transfer arm and matching corner units.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/13898-0-20240117115004.jpg",
  },
  {
    sku: "HVOF-HC-13900",
    name: "Reception Series 13900",
    category: "healthcare",
    subCategory: "Reception",
    description: "Healthcare reception seating with replaceable seat and back, healthcare-grade upholstery, 500 lb rating.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/13900-0-20240117115030.jpg",
  },
  {
    sku: "HVOF-HC-15894",
    name: "Bariatric Lounge 15894",
    category: "healthcare",
    subCategory: "Bariatric",
    description: "Bariatric-rated 1000 lb lounge chair. Reinforced frame, wide seat, removable arm caps.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/15894-0-20240105014443.jpg",
  },
  {
    sku: "HVOF-HC-20823",
    name: "Procedure Recliner 20823",
    category: "healthcare",
    subCategory: "Recliner",
    description: "Treatment-room procedure recliner. Foot-pump height adjust, full Trendelenburg, casters with toe-lock.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/20823-0.jpg",
  },
  {
    sku: "HVOF-HC-3293",
    name: "Bariatric Lounge 3293",
    category: "healthcare",
    subCategory: "Bariatric",
    description: "Wide-seat bariatric lounge. Reinforced glides, replaceable seat and back deck.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/3293-0.jpg",
  },
  {
    sku: "HVOF-HC-7161",
    name: "Modular Lobby 7161",
    category: "healthcare",
    subCategory: "Modular",
    description: "Modular lobby seating. Configurable straight, corner, and curved units with shared armrests.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/7161-0.jpg",
  },
  {
    sku: "HVOF-HC-7150",
    name: "Treatment Recliner 7150",
    category: "healthcare",
    subCategory: "Recliner",
    description: "Three-position recliner with vinyl-wrap upholstery. Casters with side brake.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/7150-0.jpg",
  },
  {
    sku: "HVOF-HC-7118",
    name: "Side Chair 7118",
    category: "healthcare",
    subCategory: "Side Chair",
    description: "Healthcare-grade side chair. Easy-clean upholstery, antimicrobial treatment, 350 lb rating.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/7118-0.jpg",
  },
  {
    sku: "HVOF-HC-6470",
    name: "Sofa 6470",
    category: "healthcare",
    subCategory: "Lounge",
    description: "Two-seat lobby sofa. Replaceable seat-back panels for fast turnover between patients.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/6470-0-20221213111915.jpg",
  },
  {
    sku: "HVOF-HC-3147",
    name: "Patient Lounge 3147",
    category: "healthcare",
    subCategory: "Lounge",
    description: "Single-seat patient lounge. Tablet-arm option, cleanable surfaces, IV-pole compatible.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/3147-0.jpg",
  },
  {
    sku: "HVOF-HC-3151",
    name: "Patient Glider 3151",
    category: "healthcare",
    subCategory: "Glider",
    description: "Therapeutic glider. Wide armrests for in-arm IV access, rocker-glide base.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/3151-0.jpg",
  },
  {
    sku: "HVOF-HC-7872",
    name: "Modular Bench 7872",
    category: "healthcare",
    subCategory: "Modular",
    description: "Tandem-bench modular seating for high-traffic lobbies. Steel frame, replaceable cushions.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/7872-0-20230307040059.jpg",
  },
  {
    sku: "HVOF-HC-7916",
    name: "Procedure Chair 7916",
    category: "healthcare",
    subCategory: "Side Chair",
    description: "Procedure-room side chair. Lift-out arm caps, single-fold rear cleaning access.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/7916-0.jpg",
  },

  // EDUCATION
  {
    sku: "HVOF-EDU-MARITIME-1",
    name: "Maritime College Classroom",
    category: "education",
    subCategory: "Classroom",
    description: "Active-learning classroom installation at Maritime College. Mobile tables, stackable seating, dual-screen prep.",
    image: "https://thewowguys.com/wp-content/uploads/2024/09/Maritime-college-1.jpg",
  },
  {
    sku: "HVOF-EDU-MARITIME-2",
    name: "Maritime College Common Area",
    category: "education",
    subCategory: "Common",
    description: "Lounge and breakout common area. Soft seating, occasional tables, study nooks, and power-charge surfaces.",
    image: "https://thewowguys.com/wp-content/uploads/2024/09/Maritime-college-2.jpg",
  },
  {
    sku: "HVOF-EDU-MARITIME-4",
    name: "Maritime Library Carrels",
    category: "education",
    subCategory: "Library",
    description: "Library carrel installation. Privacy-panel seating with task lighting and personal power.",
    image: "https://thewowguys.com/wp-content/uploads/2024/09/Maritime-college-4.jpg",
  },
  {
    sku: "HVOF-EDU-ADC-1",
    name: "ADC Active-Learning Suite",
    category: "education",
    subCategory: "Classroom",
    description: "Active-learning suite with reconfigurable tables, mobile teacher station, and tiered display walls.",
    image: "https://thewowguys.com/wp-content/uploads/2024/09/ADC1.jpg",
  },
  {
    sku: "HVOF-EDU-ADC-3",
    name: "ADC Studio Configuration",
    category: "education",
    subCategory: "Studio",
    description: "Studio-style classroom with anchored desks, mobile flip-tops, and stackable side seating.",
    image: "https://thewowguys.com/wp-content/uploads/2024/09/ADC3.jpg",
  },
  {
    sku: "HVOF-EDU-CAFE-1",
    name: "Campus Cafe Lounge",
    category: "education",
    subCategory: "Cafe",
    description: "Cafe and breakout lounge. Banquette seating, modular soft sofas, and high-top counter pairings.",
    image: "https://thewowguys.com/wp-content/uploads/2024/09/cafe1.jpg",
  },
  {
    sku: "HVOF-EDU-MARITIME-3",
    name: "Maritime Lecture Hall",
    category: "education",
    subCategory: "Lecture",
    description: "Tiered lecture hall with fixed seating, pull-out tablet arms, and integrated power.",
    image: "https://thewowguys.com/wp-content/uploads/2024/09/Maritime-college-3.jpg",
  },
  {
    sku: "HVOF-EDU-MARITIME-5",
    name: "Maritime Group Study",
    category: "education",
    subCategory: "Library",
    description: "Group-study furniture cluster with mobile whiteboards and reconfigurable tables.",
    image: "https://thewowguys.com/wp-content/uploads/2024/09/Maritime-college-5.jpg",
  },
  {
    sku: "HVOF-EDU-ADC-2",
    name: "ADC Collaboration Suite",
    category: "education",
    subCategory: "Classroom",
    description: "Collaboration suite with movable tables, stackable seating, and writable surfaces.",
    image: "https://thewowguys.com/wp-content/uploads/2024/09/ADC2.jpg",
  },
  {
    sku: "HVOF-EDU-ADC-4",
    name: "ADC Faculty Lounge",
    category: "education",
    subCategory: "Lounge",
    description: "Faculty lounge install with soft seating, occasional tables, and quiet-corner work zones.",
    image: "https://thewowguys.com/wp-content/uploads/2024/09/ADC4.jpg",
  },
  {
    sku: "HVOF-EDU-CAFE-4",
    name: "Cafe Counter Seating",
    category: "education",
    subCategory: "Cafe",
    description: "High-top counter seating with bar-height stools and pendant-lit shelves.",
    image: "https://thewowguys.com/wp-content/uploads/2024/09/cafe4.jpg",
  },
  {
    sku: "HVOF-EDU-CAFE-6",
    name: "Cafe Booth Seating",
    category: "education",
    subCategory: "Cafe",
    description: "Booth-style cafe seating in fabric-and-wood combo with table service ready.",
    image: "https://thewowguys.com/wp-content/uploads/2024/09/cafe6.jpg",
  },
  {
    sku: "HVOF-EDU-POP-5",
    name: "Pop-Up Study Lounge",
    category: "education",
    subCategory: "Lounge",
    description: "Pop-up student lounge with modular soft seating and personal-power surfaces.",
    image: "https://thewowguys.com/wp-content/uploads/2024/09/pop5.jpg",
  },

  // RECEPTION
  {
    sku: "HVOF-RECP-COE-COSMO",
    name: "COE Cosmo Reception",
    category: "reception",
    subCategory: "Reception desk",
    description: "Cosmo reception desk with transaction counter, ADA pass-through, and integrated cable channel.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/COE-Cosmo-Reception.jpg",
  },
  {
    sku: "HVOF-RECP-COE-COSMO-LSHAPE",
    name: "COE Cosmo Reception L-shape",
    category: "reception",
    subCategory: "Reception desk",
    description: "L-shape Cosmo reception desk for two-attendant front-of-house with shared queue counter.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/COE-Cosmo-Reception-L-shape.jpg",
  },
  {
    sku: "HVOF-RECP-LOGIFLEX",
    name: "Logiflex Reception Suite",
    category: "reception",
    subCategory: "Reception desk",
    description: "Logiflex modular reception. Pick laminate, veneer, or solid-surface transaction tops.",
    image: "https://thewowguys.com/wp-content/uploads/2024/06/Webpage-Product-Gallery-Desks-CollabAreas-Logiflex1.png",
  },

  // PODS, phone booths and panel systems
  {
    sku: "HVOF-POD-ROOM-SINGLE",
    name: "ROOM 1 Phone Booth",
    category: "pods",
    subCategory: "Phone booth",
    description: "Single-occupant ROOM phone booth. Sound-dampening panels, ventilation, ADA option, plug-and-play install.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/ROOM-single.png",
  },
  {
    sku: "HVOF-POD-ROOM-SINGLE-BLACK",
    name: "ROOM 1 Phone Booth, Black",
    category: "pods",
    subCategory: "Phone booth",
    description: "Single-occupant ROOM in matte black. Same acoustic specs as the white version.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/ROOM-single-black.png",
  },
  {
    sku: "HVOF-POD-ROOM-DOUBLE",
    name: "ROOM 2 Meeting Pod",
    category: "pods",
    subCategory: "Meeting pod",
    description: "2-person ROOM meeting pod. Built-in monitor mount, video-conference-ready ventilation, dimmable LED.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/ROOM-double.png",
  },
  {
    sku: "HVOF-POD-ROOM-DOUBLE-BLACK",
    name: "ROOM 2 Meeting Pod, Black",
    category: "pods",
    subCategory: "Meeting pod",
    description: "2-person ROOM in matte black. Designer-grade finish for exec floors and client-facing spaces.",
    image: "https://thewowguys.com/wp-content/uploads/2024/08/ROOM-double-black.png",
  },
  {
    sku: "HVOF-POD-DIVI-NY-SHOWROOM",
    name: "AIS Divi NY Showroom",
    category: "pods",
    subCategory: "Panel system",
    description: "Divi workstation with frameless glass, A-leg supports, sliding doors, integrated tool rail, and Devens task seating. As shown in the AIS New York showroom.",
    image: "/products/panels/ais-ny-showroom-divi-workstation-panel-system-devens-task-chair-frameless-glass-a-leg-sliding-door-tool-rail-lem-lamp-mobile-ped-lateral-file_md.jpg",
  },
  {
    sku: "HVOF-POD-DIVI-NY-2023",
    name: "AIS Divi NY 2023",
    category: "pods",
    subCategory: "Panel system",
    description: "New York showroom Divi workstation with Devens seating. Frameless glass uppers, fabric lowers, integrated mobile pedestals.",
    image: "/products/panels/new-york-showroom-2023-divi-workstation-with-devens-seating_md.jpg",
  },
  {
    sku: "HVOF-POD-DIVI-FRAMELESS",
    name: "AIS Divi with Frameless Glass",
    category: "pods",
    subCategory: "Panel system",
    description: "Divi workstation cluster with frameless-glass upmount panels. Strong sightline preservation while keeping acoustic privacy.",
    image: "/products/panels/ais-ny-showroom-divi-workstation-panel-system-devens-task-chair-frameless-glass_md.jpg",
  },
  {
    sku: "HVOF-POD-DIVI-LINEAR",
    name: "AIS Divi Linear 120-degree",
    category: "pods",
    subCategory: "Panel system",
    description: "Divi with linear trim and 120-degree worksurfaces. Creates organic clusters in open-plan layouts.",
    image: "/products/panels/divi-with-linear-trim-120-degree-worksurfaces_md.jpg",
  },
  {
    sku: "HVOF-POD-DIVI-72IN",
    name: "AIS Divi 72in Panels",
    category: "pods",
    subCategory: "Panel system",
    description: "72-inch fabric panels with glass upmount channel screens. Paired with height-adjustable tables, Calibrate storage, and Devens seating.",
    image: "/products/panels/divi-72-fabric-and-glass-upmount-channel-screens-with-height-adjustable-tables-calibrate-storage-and-devens-seating_md.jpg",
  },
  {
    sku: "HVOF-POD-DIVI-HIGH-PANELS",
    name: "AIS Divi High-Panel Privacy",
    category: "pods",
    subCategory: "Panel System",
    description: "Divi open-plan workstation with high panels for increased privacy. Right-sized for finance, legal, or focus-heavy teams.",
    image: "/products/panels/divi-open-plan-workstation-with-high-panels-for-increased-privacy_md.jpg",
  },
  {
    sku: "HVOF-POD-DIVI-O-LEG",
    name: "AIS Divi Shared Office",
    category: "pods",
    subCategory: "Panel System",
    description: "Divi shared office with O-leg worksurfaces, L-Series steel storage, and Natick seating. Compact two-person setup.",
    image: "/products/panels/divi-shared-office-with-o-leg-worksuraces-l-series-steel-storage-and-natick-seating_md.jpg",
  },
  {
    sku: "HVOF-POD-DIVI-SPINE",
    name: "AIS Divi Spine",
    category: "pods",
    subCategory: "Panel system",
    description: "Divi spine in open-plan applications with Devens seating. High-density floor planning for engineering and creative teams.",
    image: "/products/panels/divi-spine-in-open-plan-applications-and-devens-seating_md.jpg",
  },
  {
    sku: "HVOF-POD-DIVI-NEOCON-2021",
    name: "AIS Divi NeoCon 2021",
    category: "pods",
    subCategory: "Panel system",
    description: "Divi Linear with gallery panels and Calibrate storage. Shown with Essex seating at NeoCon 2021.",
    image: "/products/panels/neocon-2021-divi-linear-with-gallery-panels-and-calibrate-storage-shown-with-essex-seating_md.jpg",
  },

  // PRE-OWNED
  {
    sku: "HVOF-PRE-001",
    name: "Pre-owned Executive Suite, Lot 001",
    category: "preowned",
    subCategory: "Executive",
    description: "Inspected, cleaned, and warranted in-house. Walnut executive desk with matching storage. One available.",
    image: "https://thewowguys.com/wp-content/uploads/2024/10/image00001.jpeg",
  },
  {
    sku: "HVOF-PRE-002",
    name: "Pre-owned Task Chair Lot, 002",
    category: "preowned",
    subCategory: "Seating",
    description: "Mesh-back task chairs, lot of 12. Reupholstered, casters and pneumatic lift replaced.",
    image: "https://thewowguys.com/wp-content/uploads/2024/10/image00002.jpeg",
  },
  {
    sku: "HVOF-PRE-003",
    name: "Pre-owned Conference Table, 003",
    category: "preowned",
    subCategory: "Conference",
    description: "10 ft conference table. Refinished top, base inspected, ready to install.",
    image: "https://thewowguys.com/wp-content/uploads/2024/10/image00003.jpeg",
  },
  {
    sku: "HVOF-PRE-004",
    name: "Pre-owned Sit-Stand Desks, 004",
    category: "preowned",
    subCategory: "Sit-Stand",
    description: "Set of 6 electric sit-stand desks. Tested through full travel range, controllers swapped to current spec.",
    image: "https://thewowguys.com/wp-content/uploads/2024/10/image00004.jpeg",
  },
  {
    sku: "HVOF-PRE-005",
    name: "Pre-owned Reception, 005",
    category: "preowned",
    subCategory: "Reception",
    description: "L-shape reception desk in good cosmetic condition. Refinished transaction counter.",
    image: "https://thewowguys.com/wp-content/uploads/2024/10/image00005.jpeg",
  },
  {
    sku: "HVOF-PRE-006",
    name: "Pre-owned Panel System Set, 006",
    category: "preowned",
    subCategory: "Panels",
    description: "Set of 8 fabric-panel workstations, 64 in heights. Power harnesses tested and rebuilt.",
    image: "https://thewowguys.com/wp-content/uploads/2024/10/image00006.jpeg",
  },
  {
    sku: "HVOF-PRE-007",
    name: "Pre-owned Lounge Set, 007",
    category: "preowned",
    subCategory: "Lounge",
    description: "Tier-A lobby lounge set. Sofa, two armchairs, and matching coffee table.",
    image: "https://thewowguys.com/wp-content/uploads/2024/10/image00007.jpeg",
  },
  {
    sku: "HVOF-PRE-008",
    name: "Pre-owned Boardroom Chairs, 008",
    category: "preowned",
    subCategory: "Conference",
    description: "Set of 12 leather-wrap boardroom chairs. Refoamed cushions, casters re-greased.",
    image: "https://thewowguys.com/wp-content/uploads/2024/10/image00008.jpeg",
  },
  {
    sku: "HVOF-PRE-010",
    name: "Pre-owned Workstation, 010",
    category: "preowned",
    subCategory: "Workstation",
    description: "Single-user workstation with integrated overhead and pedestal storage.",
    image: "https://thewowguys.com/wp-content/uploads/2024/10/image00010.jpeg",
  },
  {
    sku: "HVOF-PRE-012",
    name: "Pre-owned Filing System, 012",
    category: "preowned",
    subCategory: "Storage",
    description: "Lateral-file system, set of 6. Locks rebuilt, trays cleaned, ready to ship.",
    image: "https://thewowguys.com/wp-content/uploads/2024/10/image00012.jpeg",
  },
  {
    sku: "HVOF-PRE-015",
    name: "Pre-owned Side Tables, 015",
    category: "preowned",
    subCategory: "Tables",
    description: "Set of 4 lobby side tables. Inspected veneer, refinished tops.",
    image: "https://thewowguys.com/wp-content/uploads/2024/10/image00015.jpeg",
  },
];

export function getProductsByCategory(category: ProductCategory) {
  return PRODUCTS.filter((p) => p.category === category);
}

export function getProductBySku(sku: string) {
  return PRODUCTS.find((p) => p.sku === sku);
}

export function formatPrice(price: number) {
  return `$${price.toLocaleString("en-US")}`;
}
